version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
install:
- ps: >-
    cd src
    
    nuget restore OpenSage.sln
build:
  project: src/OpenSage.sln
  verbosity: minimal
artifacts:
- path: src\OpenSage.DataViewer.Windows\bin\Release\net462\*.*
  name: Data Viewer
- path: src\OpenSage.Launcher\bin\Release\netcoreapp2.0\*.*
  name: Launcher